googleAnalytics = "G-BZYESZDTPC"
baseURL = "https://alexsanchez.design"

enableRobotsTXT = true
canonifyURLs = true

languageCode = "en-us"
languageName = "English"

title = "Alex Sanchez | Orange County Web Designer"

[params]
description = "Trying to do everything yourself is stressful. So focus on running your business, and leave the website to me."
og_image = '/img/opengraph.webp'
sitename = "Alex Sanchez | Orange County Web Designer"
twitter = "@ansolvera"

author = "Alex Sanchez"
copyright = "Copyright © ANSO Enterprises, LLC | All rights reserved."

[build]
writeStats = true
